## Widgets
CONST_WIDGET_BUTTON_SAVE            = 7000
CONST_WIDGET_BUTTON_OPEN            = 7001
CONST_WIDGET_BUTTON_NEW             = 7002
CONST_WIDGET_PROJECT_OPEN           = 7003
CONST_WIDGET_PROJECT_LIST           = 7004
CONST_WIDGET_PROJECT_PANEL          = 7005
CONST_WIDGET_PROJECT_LIST_PANEL     = 7006
CONST_WIDGET_PROJECT_BUTTON_OPEN    = 7007
CONST_WIDGET_PROJECT_BUTTON_CANCEL  = 7008
CONST_WIDGET_PROJECT_BUTTON_DELETE  = 7009
CONST_WIDGET_PROJECT_TREE           = 7010



## Pane
CONST_PANE_MAIN_BUTTONS     = 8000

## Menu Entries
CONST_MENU_PROJECT_NEW      = 9000
CONST_MENU_PROJECT_OPEN     = 9001
CONST_MENU_FILE_OPEN        = 9002
CONST_MENU_FILE_SAVE_AS     = 9003
CONST_MENU_FILE_SAVE        = 9004
CONST_MENU_FILE_NEW         = 9005
CONST_MENU_EXIT             = 9006
CONST_MENU_ABOUT            = 9007
CONST_MENU_PREFERENCES      = 9008